[platformio]
build_cache_dir = .pio/build_cache

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_extra_dirs = ../../..

; remove gnu++11, add gnu++20 (with GCC ext)
build_unflags = -std=gnu++11
build_flags = -std=gnu++20
monitor_speed = 115200