[platformio]
lib_dir = .
src_dir = src
build_cache_dir = .pio/build_cache


[env:base]
test_framework = unity

lib_deps = 
    throwtheswitch/Unity

lib_ignore = 
    Unity/examples/example_1

monitor_speed = 115200

build_flags = 
    -Isrc
    -Itest
    -std=gnu++20
    -D NO_GLOBAL_INSTANCES

build_unflags = 
    -std=gnu++11


[env:native]
extends = env:base

platform = native

test_filter = unit/*


[env:esp32dev]
extends = env:base

platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino

board = esp32dev
