# Copyright (c) 2026 KiraFlux
# SPDX-License-Identifier: MIT
#
# KiraFlux Toolkit – Root Project Configuration
#
# This is the main PlatformIO configuration for the KiraFlux Toolkit library.
# It sets up build and test environments for both ESP32 and native platforms.
# - Default build target: esp32dev
# - Unity framework is used for unit tests (located in test/unit/)
# - Common build flags apply to all environments
# Repository: https://github.com/KiraFlux/KiraFlux-Toolkit

[platformio]
lib_dir = .
src_dir = src
build_cache_dir = .pio/build_cache

default_envs = esp32dev


[env]
test_framework = unity

lib_deps = 
    throwtheswitch/Unity

lib_ignore = 
    Unity/examples/example_1

build_flags = 
    -Isrc
    -Itest
    -std=gnu++20
    -D NO_GLOBAL_INSTANCES

monitor_speed = 115200


[env:native]
platform = native

test_filter = unit/*


[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino

board = esp32dev
