[platformio]
lib_dir = .
src_dir = src
build_cache_dir = .pio/build_cache

[env:native]
platform = native
test_framework = unity
build_unflags = -std=gnu++11
build_flags = 
    -Isrc
    -Itest
    -std=gnu++17
lib_deps = throwtheswitch/Unity
lib_ignore = Unity/examples/example_1
test_filter = unit/*

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
test_framework = unity
build_unflags = -std=gnu++11
build_flags = 
    -Isrc
    -Itest
    -std=gnu++17
lib_deps = throwtheswitch/Unity
lib_ignore = Unity/examples/example_1