; KiraFlux-Toolkit Example Project configuration
[platformio]
build_cache_dir = .pio/build_cache

[env:example]
build_unflags = -std=gnu++11
build_flags = -std=gnu++20
lib_extra_dirs = ../../..
monitor_speed = 115200

[env:esp32dev]
extends = env:example
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino

[env:native]
extends = env:example
platform = native
