name: Lint

on:
  pull_request:
    branches: [ dev, main ]

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install PlatformIO
        run: pip install platformio

      - name: Generate compile_commands.json
        run: pio run --target compiledb

      - name: Set lint mode
        id: lint-mode
        run: |
          if [[ "${{ github.base_ref }}" == "main" ]]; then
            echo "files-changed-only=false" >> $GITHUB_OUTPUT
          else
            echo "files-changed-only=true" >> $GITHUB_OUTPUT
          fi

      - name: Run cpp-linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'                                     # use .clang-format 
          tidy-checks: ''                                   # use .clang-tid
          files-changed-only: ${{ steps.lint-mode.outputs.files-changed-only }}
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
          step-summary: true
          database: 'compile_commands.json'

      - name: Fail if issues found
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1